#!/bin/bash
apt update -y
apt install python3-pip -y
pip3 install Flask

cat <<EOF > /home/ubuntu/app.py
from flask import Flask
app=Flask(__name__)

@app.route("/")
def home():
    return "NLB Auto Scaling Demo"

app.run(host="0.0.0.0",port=5000)
EOF

python3 /home/ubuntu/app.py &
